language: rust
cache: cargo
rust: stable

before_script:
  - rustup component add clippy-preview
  - cargo clippy --version

script:
  - cargo build --verbose
  - cargo test  --verbose
  - cargo clippy